config/routes.rb
IViaggiManager::Application.routes.draw do

  resources :tour_operators do
    resources :catalogs, :shallow => true
  end

  root 'tour_operators#index'

  

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  belongs_to :tour_operator
end

app/models/tour_operator.rb
class TourOperator < ActiveRecord::Base
  has_many :catalogs

  has_attached_file :icon, :styles => { :small => "32x32>", :medium => "64x64>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  private
  def set_locale
    I18n.locale = params[:locale] if params[:locale]
  end
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  before_action :set_catalog, only: [:show, :edit, :update, :destroy]

  # GET /catalogs
  # GET /catalogs.json
  def index
    @catalogs = Catalog.where(:tour_operator_id => params[:tour_operator_id])

    respond_to do |format|
      format.html
      format.json
      format.js
    end
  end

  # GET /catalogs/1
  # GET /catalogs/1.json
  def show
  end

  # GET /catalogs/new
  def new
    @catalog = Catalog.new(:tour_operator_id => params[:tour_operator_id])
  end

  # GET /catalogs/1/edit
  def edit
  end

  # POST /catalogs
  # POST /catalogs.json
  def create
    @catalog = Catalog.new(catalog_params)

    respond_to do |format|
      if @catalog.save
        format.html { redirect_to catalog_path(@catalog), notice: 'Catalog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @catalog }
      else
        format.html { render action: 'new' }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogs/1
  # PATCH/PUT /catalogs/1.json
  def update
    respond_to do |format|
      if @catalog.update(catalog_params)
        format.html { redirect_to catalog_path(@catalog), notice: 'Catalog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogs/1
  # DELETE /catalogs/1.json
  def destroy
    @catalog.destroy
    respond_to do |format|
      format.html { redirect_to tour_operator_catalogs_url(@catalog.tour_operator) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog
      @catalog = Catalog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catalog_params
      params.require(:catalog).permit(:title, :destination, :url, :tour_operator_id)
    end
end

app/controllers/tour_operators_controller.rb
class TourOperatorsController < ApplicationController
  before_action :set_tour_operator, only: [:show, :edit, :update, :destroy]

  # GET /tour_operators
  # GET /tour_operators.json
  def index
    @tour_operators = TourOperator.all
  end

  # GET /tour_operators/1
  # GET /tour_operators/1.json
  def show
  end

  # GET /tour_operators/new
  def new
    @tour_operator = TourOperator.new
  end

  # GET /tour_operators/1/edit
  def edit
  end

  # POST /tour_operators
  # POST /tour_operators.json
  def create
    @tour_operator = TourOperator.new(tour_operator_params)

    respond_to do |format|
      if @tour_operator.save
        format.html { redirect_to @tour_operator, notice: 'Tour operator was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tour_operator }
      else
        format.html { render action: 'new' }
        format.json { render json: @tour_operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tour_operators/1
  # PATCH/PUT /tour_operators/1.json
  def update
    respond_to do |format|
      if @tour_operator.update(tour_operator_params)
        format.html { redirect_to @tour_operator, notice: 'Tour operator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tour_operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_operators/1
  # DELETE /tour_operators/1.json
  def destroy
    @tour_operator.destroy
    respond_to do |format|
      format.html { redirect_to tour_operators_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour_operator
      @tour_operator = TourOperator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_operator_params
      params[:tour_operator]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def shallow_args(parent, child)
    child.try(:new_record?) ? [parent, child] : child
  end
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/tour_operators_helper.rb
module TourOperatorsHelper
end

app/views/catalogs/_form.html.erb
<%= form_for shallow_args(@catalog.tour_operator, @catalog), :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :destination, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :destination, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tour_operator_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :tour_operator_id, TourOperator.all(order: 'name'), :id, :name, :class => 'select_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tour_operator_catalogs_path(@catalog.tour_operator), :class => 'btn' %>
  </div>
<% end %>

app/views/catalogs/_index.html.erb
<%- model_class = Catalog -%>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:title) %></th>
    <th><%= model_class.human_attribute_name(:destination) %></th>
    <th><%= model_class.human_attribute_name(:url) %></th>
    <th><%= model_class.human_attribute_name(:tour_operator_id) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @catalogs.each do |catalog| %>
      <tr>
        <td><%= link_to catalog.id, catalog_path(catalog) %></td>
        <td><%= catalog.title %></td>
        <td><%= catalog.destination %></td>
        <td><%= catalog.url %></td>
        <td><%= link_to catalog.tour_operator.name, tour_operator_path(catalog.tour_operator) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_catalog_path(catalog), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      catalog_path(catalog),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tour_operator_catalog_path(:tour_operator_id => params[:tour_operator_id]),
            :class => 'btn btn-primary' %>

app/views/catalogs/edit.html.erb
<%- model_class = Catalog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/catalogs/index.html.erb
<%- model_class = Catalog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= render :partial => 'index' %>

app/views/catalogs/index.js.erb
$('div#catalogs').html('<%=j render :partial => 'index' %>');
$('div#catalogs').show();

app/views/catalogs/new.html.erb
<%- model_class = Catalog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/catalogs/show.html.erb
<%- model_class = Catalog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @catalog.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:destination) %>:</strong></dt>
  <dd><%= @catalog.destination %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @catalog.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tour_operator) %>:</strong></dt>
  <dd><%= @catalog.tour_operator.name %><%= image_tag @catalog.tour_operator.icon.url(:small) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tour_operator_catalogs_path(@catalog.tour_operator), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_catalog_path(@catalog), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              catalog_path(@catalog),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IViaggiManager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

<div>
  <%= t :hello %> (<%= locale %>) <%= t :catalog, count: 200 %>
</div>
</body>
</html>

app/views/tour_operators/_form.html.erb
<%= form_for @tour_operator, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :icon, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :icon, :class => 'file_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tour_operators_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tour_operators/edit.html.erb
<%- model_class = TourOperator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tour_operators/index.html.erb
<%- model_class = TourOperator -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div class="container">
  <div class="row">
    <div class="span6">

      <table class="table table-striped">
        <thead>
        <tr>
          <th>&nbsp;</th>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:url) %></th>
          <th><%= t '.actions', :default => t("helpers.actions") %></th>
        </tr>
        </thead>
        <tbody>
        <% @tour_operators.each do |tour_operator| %>
            <tr>

              <td><%= image_tag tour_operator.icon.url(:small) %></td>
              <td><%= link_to tour_operator.id, tour_operator_path(tour_operator) %></td>
              <td><%= link_to tour_operator.name, tour_operator_catalogs_path(tour_operator), remote: true %></td>
              <td><%= tour_operator.url %></td>
              <td>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_tour_operator_path(tour_operator), :class => 'btn btn-mini' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            tour_operator_path(tour_operator),
                            :method => :delete,
                            :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                            :class => 'btn btn-mini btn-danger' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_tour_operator_path,
                  :class => 'btn btn-primary' %>

    </div>
    <div class="span6">
      <div id="catalogs"></div>
    </div>
  </div>
</div>

app/views/tour_operators/new.html.erb
<%- model_class = TourOperator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tour_operators/show.html.erb
<%- model_class = TourOperator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><%= image_tag @tour_operator.icon.url(:medium) %></dt>
  <dd><%= @tour_operator.name %></dd>
  <dd><%= @tour_operator.url %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tour_operators_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tour_operator_path(@tour_operator), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tour_operator_path(@tour_operator),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>